export const demoTenureEmployees = [
  {
    comp: "SDL",
    code: "05254",
    name: "Jagajit Singh",
    designation: "Sales Officer",
    location: "Bhubaneshwar",
    department: "Sales",
    employeeType: "Probationary",
    dateOfJoining: "24-Apr-2025",
    tenureDueDate: "02-NOV-2025",
    apprLevel: "1.Chitta Nath",
    managerName: "Chitta Nath",
    mgr_code: "04797",
    orgId: "169",
    currentCtc: "252000",
  },
  {
    comp: "SDL",
    code: "05063",
    name: "Prathmesh Chavan",
    designation: "P.S.R",
    location: "	Pune-2",
    department: "Sales",
    employeeType: "Trainee",
    dateOfJoining: "05-Nov-2024",
    tenureDueDate: "05-NOV-2025",
    apprLevel: "1.Vivek Daddikar",
    managerName: "Vivek Daddikar",
    mgr_code: "03930",
    orgId: "154",
    currentCtc: "252000",
  },
  {
    comp: "SDL",
    code: "05262",
    name: "Palash Chahande",
    designation: "P.S.R",
    location: "Nagpur-2",
    department: "Sales",
    employeeType: "Probationary",
    dateOfJoining: "02-May-2025",
    tenureDueDate: "06-NOV-2025",
    apprLevel: "1.Mangesh Joshi",
    managerName: "Mangesh Joshi",
    mgr_code: "03951",
    orgId: "154",
    currentCtc: "252000",
  },
  {
    comp: "SDL",
    code: "05683",
    name: "Dipali Mane",
    designation: "Chemist",
    location: "SDLPN",
    department: "Production",
    employeeType: "Probationary",
    dateOfJoining: "16-Apr-2026",
    tenureDueDate: "16-Oct-2026",
    apprLevel: "1.Vivek Daddikar",
    managerName: "Vivek Daddikar",
    mgr_code: "03930",
    currentCtc: "252000",
    orgId: "169",
  },
];

export const demoTenureEmployee = demoTenureEmployees[0];

export const tenureRatingQuestions = [
  "Punctuality",
  "Attendance",
  "Dressing Sense/Appearance",
  "Inter Personal Skills",
  "Communication Skill",
  "Grasping Power",
  "Attitude For Learning",
  "Selling Skills",
  "Perseverance",
  "Time Management",
  "Energy Level",
  "Dependability",
];

export const tenureRatingOptions = [
  "Excellent",
  "Very Good",
  "Good",
  "Average",
  "Below Average",
];

export const tenureTypeOptions = [
  "Permanent",
  "Trainee Extension",
  "Contract Extension",
  "Probation Extension",
  "Probation",
  "Trainee To Probation",
];
